Server:
  port: 8080

spring:
  application:
    name: order-service
  profiles:
    active: @profile.name@
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/cloud_order?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 8.138.46.63:8848

#        cluster-name: BJ
    loadbalancer:
      nacos:
        enabled: true
mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true