Server:
  port: 9090

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/cloud_product?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 8.138.46.63:8848
#        cluster-name: BJ

mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true